# Site settings
title: Andre's Random Thoughts
email: andre42m@gmail.com
description: >
  Just another blog about programming, hacks and anything else that comes up
  to a curious and bit mad(who's not?) software devoloper's mind.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreldm.com" # the base hostname & protocol for your site
github_username:  andreldm

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
