# Site settings
title: Andre's 2&cent;
email: andre42m@gmail.com
description: >
  A blog dedicated toprogramming tricks (mostly JavaScript and Java...),
  Libraries & Frameworks, software design & architecture, Tools, Linux related
  things and anything else I find meaningful and useful to share.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreldm.com" # the base hostname & protocol for your site
github_username:  andreldm

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
